# Codacy config file
# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

# Exclude assert checks within tests
assert_used:
  skips: ['*_test.py', 'test_*.py', '**/*_test.py', '**/test_*.py', '*/test_*.py']
