user_input = {
    "url": "https://art.gsa.gov/",
    "wait": 2,
    "screenshots": True,
    "output_main": {
        "request": True,
        "format": "png",
        "doc_pad_h": 30,
        "doc_pad_v": 20,
        "doc_fill_color": "#FFFFFF",
        "base_stroke_color": "#23445D",
        "base_fill_color": "#BAC8D3",
    },
    "output_browser": {
        "request": True,
        "format": "png",
        "doc_pad_h": 30,
        "doc_pad_v": 20,
        "doc_fill_color": "#FFFFFF",
        "base_stroke_color": "#23445D",
        "base_fill_color": "#BAC8D3",
    },
    "output_mobiles": {
        "request": True,
        "format": "png",
        "doc_pad_h": 30,
        "doc_pad_v": 20,
        "doc_fill_color": "#FFFFFF",
        "base_stroke_color": "#23445D",
        "base_fill_color": "#BAC8D3",
    },
        "output_full": {
        "request": True,
        "format": "png",
        "doc_pad_h": 30,
        "doc_pad_v": 20,
        "doc_fill_color": "#FFFFFF",
        "base_stroke_color": "#23445D",
        "base_fill_color": "#BAC8D3",
    },
        "output_video": {
        "request": True,
        "format": "png",
        "doc_pad_h": 50,
        "doc_pad_v": 40,
        "doc_fill_color": "#FFFFFF",
        "base_stroke_color": "#23445D",
        "base_fill_color": "#BAC8D3",
    },
}


# ################################################## #
#
# DO NOT EDIT below this comment.
#
# ################################################## #
system_input = {
    "desktop": {
        "filename_large": "screenshot_desktop_large.png",
        "width_large": 2160,
        "height_large": 1360,
        "filename_medium": "screenshot_desktop_medium.png",
        "width_medium": 2048,
        "height_medium": None,
        "medium_height_crop": 1152,
        "filename_small": "screenshot_desktop_small.png",
        "width_small": 1920,
        "height_small": None,
        "small_height_crop": 1080,
    },
    "laptop": {
        "filename_large": "screenshot_laptop_large.png",
        "width_large": 1440,
        "height_large": 900,
        "filename_medium": "screenshot_laptop_medium.png",
        "width_medium": None,
        "height_medium": None,
        "medium_height_crop": None,
        "filename_small": "screenshot_laptop_small.png",
        "width_small": 1280,
        "height_small": None,
        "small_height_crop": 720,
    },
    "tablet": {
        "filename_large": "screenshot_tablet_large.png",
        "width_large": 768,
        "height_large": 1024,
        "filename_medium": "screenshot_tablet_medium.png",
        "width_medium": 1016,
        "height_medium": None,
        "medium_height_crop": 1336,
        "filename_small": "screenshot_tablet_small.png",
        "width_small": 600,
        "height_small": None,
        "small_height_crop": 800,
    },
    "smartphone": {
        "filename_large": "screenshot_smartphone_large.png",
        "width_large": 430,
        "height_large": 932,
        "filename_medium": "screenshot_smartphone_medium.png",
        "width_medium": 360,
        "height_medium": None,
        "medium_height_crop": 760,
        "filename_small": "screenshot_smartphone_small.png",
        "width_small": 230,
        "height_small": None,
        "small_height_crop": 490,
    },
    "full": {
        "filename_large": "screenshot_full_large.png",
        "width_large": 2160,
        "height_large": 1360,
        "filename_medium": "screenshot_full_medium.png",
        "width_medium": 2048,
        "height_medium": None,
        "medium_height_crop": 1152,
        "filename_small": "screenshot_full_small.png",
        "width_small": 768,
        "height_small": None,
        "small_height_crop": 1024,
    },
    "video": {
        "filename_large": "movie_large.mp4",
        "width_large": 1280,
        "height_large": 720,
        "filename_medium": "movie_medium.mp4",
        "width_medium": None,
        "height_medium": None,
        "medium_height_crop": None,
        "filename_small": "movie_small.mp4",
        "width_small": None,
        "height_small": None,
        "small_height_crop": None,
    },
}